//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feedback.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reaction
    {
        public int reactId { get; set; }
        public int reactBit { get; set; }
        public int commentId { get; set; }
        public string userEmail { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
